name: RDS Deploy
description: Deploy an AWS RDS Cluster using Terraform
inputs:
  cluster_identifier:
    description: 'RDS Endpoint'
    default: 'default-aurora-mysql'
    required: true
  dbname:
    description: 'Database name to create'
    default: ''
    required: true

runs:
  using: docker
  image: Dockerfile
